file_format: "1"
id: cirquespitest01
name: cirquespitest01
type: shield
url: https://github.com/ShiniNet/zmk-config01/
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
siblings:
  - cirquespitest01_left
  - cirquespitest01_right
